<?php

/**
 * @file
 * Farm eggs.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_farm_entity_bundle_field_info().
 *
 * Adds 'Produces eggs' field to group and animal assets.
 */
function farm_eggs_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle): array {
  $fields = [];
  if ($entity_type->id() == 'asset' && in_array($bundle, ['group', 'animal'])) {
    $options = [
      'type' => 'boolean',
      'label' => t('Produces eggs'),
      'description' => t('Checking this box will make this asset available in the <a href="@egg_form_path">egg harvest form</a>.', ['@egg_form_path' => '/quick/eggs']),
      'weight' => [
        'form' => 30,
        'view' => -30,
      ],
    ];
    $fields['produces_eggs'] = \Drupal::service('farm_field.factory')->bundleFieldDefinition($options);
  }
  return $fields;
}
